-- PROD 테이블의 모든 컬럼의 자료 조회
SELECT *
FROM PROD;

-- PROD 테이블에서 PROD_ID, PROD_NAME 컬럼의 자료만 조회
SELECT PROD_ID, PROD_NAME
FROM PROD;

-- RROD 테이블에서 PROD_PRICE 컬럼의 자료만 조회
SELECT PROD_PRICE
FROM PROD;

-- PROD 테이블에서 PROD_NAME 컬럼의 자료만 조회
SELECT PROD_NAME
FROM PROD;
